/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CelciusToFahrenheit;

/**
 *
 * @author Fadhilansyah25
 */
public class CelciusToFahrenheit extends javax.swing.JFrame {

    /**
     * Creates new form CelciusToFahrenheit
     */
    public CelciusToFahrenheit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCelciusToFahrenheit_FadilArdiansyah = new javax.swing.JPanel();
        CelciusField_FadilArdiansyah = new javax.swing.JTextField();
        ConvertButton_FadilArdiansyah = new javax.swing.JButton();
        CelciusLabel_FadilArdiansyah = new javax.swing.JLabel();
        FahrenheitLabel_FadilArdiansyah = new javax.swing.JLabel();
        ClearButton_FadilArdiansyah = new javax.swing.JButton();
        ExitButton_FadilArdiansyah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConvertButton_FadilArdiansyah.setText("Convert");
        ConvertButton_FadilArdiansyah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertButton_FadilArdiansyahActionPerformed(evt);
            }
        });

        CelciusLabel_FadilArdiansyah.setText("Celcius");

        FahrenheitLabel_FadilArdiansyah.setText("Fahrenheit");

        ClearButton_FadilArdiansyah.setText("CLEAR");
        ClearButton_FadilArdiansyah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButton_FadilArdiansyahActionPerformed(evt);
            }
        });

        ExitButton_FadilArdiansyah.setText("EXIT");
        ExitButton_FadilArdiansyah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton_FadilArdiansyahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCelciusToFahrenheit_FadilArdiansyahLayout = new javax.swing.GroupLayout(PanelCelciusToFahrenheit_FadilArdiansyah);
        PanelCelciusToFahrenheit_FadilArdiansyah.setLayout(PanelCelciusToFahrenheit_FadilArdiansyahLayout);
        PanelCelciusToFahrenheit_FadilArdiansyahLayout.setHorizontalGroup(
            PanelCelciusToFahrenheit_FadilArdiansyahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCelciusToFahrenheit_FadilArdiansyahLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(PanelCelciusToFahrenheit_FadilArdiansyahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CelciusField_FadilArdiansyah)
                    .addComponent(ConvertButton_FadilArdiansyah, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(ClearButton_FadilArdiansyah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(PanelCelciusToFahrenheit_FadilArdiansyahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitButton_FadilArdiansyah)
                    .addGroup(PanelCelciusToFahrenheit_FadilArdiansyahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CelciusLabel_FadilArdiansyah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FahrenheitLabel_FadilArdiansyah, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        PanelCelciusToFahrenheit_FadilArdiansyahLayout.setVerticalGroup(
            PanelCelciusToFahrenheit_FadilArdiansyahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCelciusToFahrenheit_FadilArdiansyahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCelciusToFahrenheit_FadilArdiansyahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CelciusField_FadilArdiansyah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CelciusLabel_FadilArdiansyah))
                .addGap(18, 18, 18)
                .addGroup(PanelCelciusToFahrenheit_FadilArdiansyahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertButton_FadilArdiansyah)
                    .addComponent(FahrenheitLabel_FadilArdiansyah))
                .addGap(29, 29, 29)
                .addGroup(PanelCelciusToFahrenheit_FadilArdiansyahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton_FadilArdiansyah)
                    .addComponent(ExitButton_FadilArdiansyah))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCelciusToFahrenheit_FadilArdiansyah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCelciusToFahrenheit_FadilArdiansyah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertButton_FadilArdiansyahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertButton_FadilArdiansyahActionPerformed
        // TODO add your handling code here:
        double Fahrenheit_FadilArdiansyah = Double.parseDouble(CelciusField_FadilArdiansyah.getText()) * 1.8 + 32;
        FahrenheitLabel_FadilArdiansyah.setText(Fahrenheit_FadilArdiansyah + " Fahrenheit");
    }//GEN-LAST:event_ConvertButton_FadilArdiansyahActionPerformed

    private void ClearButton_FadilArdiansyahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButton_FadilArdiansyahActionPerformed
        // TODO add your handling code here:
        CelciusField_FadilArdiansyah.setText("");
        FahrenheitLabel_FadilArdiansyah.setText("Fahrenheit");
        CelciusField_FadilArdiansyah.requestFocus();
    }//GEN-LAST:event_ClearButton_FadilArdiansyahActionPerformed

    private void ExitButton_FadilArdiansyahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton_FadilArdiansyahActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButton_FadilArdiansyahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CelciusToFahrenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CelciusToFahrenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CelciusToFahrenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CelciusToFahrenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CelciusToFahrenheit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CelciusField_FadilArdiansyah;
    private javax.swing.JLabel CelciusLabel_FadilArdiansyah;
    private javax.swing.JButton ClearButton_FadilArdiansyah;
    private javax.swing.JButton ConvertButton_FadilArdiansyah;
    private javax.swing.JButton ExitButton_FadilArdiansyah;
    private javax.swing.JLabel FahrenheitLabel_FadilArdiansyah;
    private javax.swing.JPanel PanelCelciusToFahrenheit_FadilArdiansyah;
    // End of variables declaration//GEN-END:variables
}
